# Guardfile for orm_sampler
# More info at https://github.com/guard/guard#readme

# parameters:
#  output     => the formatted to use
#  backtrace  => number of lines, nil =  everything
guard 'bacon', :output => "BetterOutput", :backtrace => 4 do
  watch(%r{^lib/(.+)\.rb$})     { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r{^spec/spec_helper\.rb$}) { |m| Dir['spec/**/*_spec.rb'] }
  watch(%r{^spec/(?!fixtures/)(?!tmp/).+\.rb$})
end

